repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']

  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        language: system
        entry: shfmt --write --indent 2 --case-indent --binary-next-line --simplify --language-dialect bash
        types: [shell]
        exclude: '(\.zshrc|\.p10k\.zsh|z\.sh|\.dotfilesrc|\.lessfilter)$'

  - repo: https://github.com/psf/black
    rev: '26.3.1'
    hooks:
      - id: black
