#!/usr/bin/env bash

cert=$(~/bin/acm-pca | fzf | awk '{print $2}')

cert=$(echo $cert | tr -d '"')
aws acm-pca update-certificate-authority --certificate-authority-arn $cert --status DISABLED
aws acm-pca delete-certificate-authority --certificate-authority-arn $cert
