#!/usr/bin/env bash
set -euo pipefail

function usage {
    cat <<EOF
Usage: ./$0 [-a account_nubmer]

Prints out the amis for the given account

Args:
    -a ACCOUNT_NUMBER       An aws account to query for amis
EOF
}

while getopts "o:a:hv" OPTION; do
    case $OPTION in
        o)
            OWNER=$OPTARG
            shift
            ;;
        a)
            ACCOUNT=$OPTARG
            shift
            ;;
        h)
            usage
            exit 1
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

ARG=${1:-}
AWS_ARGS=""

case "$ARG" in
    ami-*)
        AWS_ARGS="--image-ids $ARG"
        ;;
esac

case "$OWNER" in
    self)
        AWS_ARGS="$AWS_ARGS --owners self"
        ;;
    *)
        AWS_ARGS="$AWS_ARGS --owners $OWNER"
        ;;
esac

if [[ "${ACCOUNT:-invalid}" == "invalid" ]]; then
    ACCOUNT=$(aws sts get-caller-identity | jq .Account -r)
fi

aws ec2 describe-images --executable-users "$ACCOUNT" $AWS_ARGS |
    jq -r '.Images[] | [.CreationDate, .ImageId, .Name, .Desription] | @tsv' | sort | column -t
