#!/usr/bin/env bash
set -euo pipefail

function usage {
    cat << EOF
Usage: ./$0 [-a account_nubmer]

Prints out the amis for the given account

Args:
    -a ACCOUNT_NUMBER       An aws account to query for amis
EOF
}


while getopts "a:hv" OPTION
do
     case $OPTION in
         a)
             ACCOUNT=$OPTARG;;
         h)
             usage
             exit 1
             ;;
     esac
done

if [[ "${ACCOUNT:-invalid}" == "invalid" ]]; then
    ACCOUNT=$(aws sts get-caller-identity | jq .Account -r)
fi


aws ec2 describe-images  --owners $ACCOUNT |\
    jq -r '.Images[] | [.CreationDate, .ImageId, .Name, .Desription] | @csv' | \
    sort | tr -d '"'
