#!/usr/bin/env bash
set -euo pipefail

command -v bat &>/dev/null || {
    brew install bat
}

source $HOME/bin/.lib
PATH=$(sed "s@$HOME/bin:@@" <<<"$PATH")

case $(which cat) in
    *coreutils*) : ;;
    *) brew install coreutils ;;
esac

if [[ "$*" =~ "p10k-instant-prompt-output" ]]; then
    /bin/cat "$@"
elif [[ $SHLVL -gt 2 ]]; then
    cat "$@"
else
    bat "$@"
fi
