#!/usr/bin/env bash
set -euo pipefail

URL=$1

die() {
    echo "$*" 1>&2
    exit 1
}

if [[ -z $URL ]]; then
    die "Error, please provide URL to clone"
fi

dest=${URL/https:\/\//~/code/}
dest=${dest/http:\/\//~/code/}
dest=${dest/git@github.com:/~/code/github.com/}
dest=${dest/git@gitlab.com:/~/code/gitlab.com/}
dest=${dest/.git/}

cmd="git clone $URL $dest"
if [[ "${DRY:-}" == "true" ]]; then
    echo "dry $cmd"
    exit 0
fi

eval "$cmd"

if [[ -f $dest/.pre-commit-config.yaml ]]; then
    cd "$dest" && pre-commit install
fi
