#! /usr/bin/env bash
#

set -euo pipefail

AP='ansible-playbook'
SUDO='sudo'

if [[ -f /.dockerenv ]]; then
    SUDO=''
fi

if [[ ! -f ~/bin/dotfiles/dotfiles.yml ]]; then
    # this is the first time that we are running dfl, so clone the
    # repository and then start that dfl.
    which git &> /dev/null || {
        apt-get install -y git 2> /tmp/apt-get-install-git.txt || {
            grep 'E: Unable to locate package git' /tmp/apt-get-install-git.txt  && {
                apt-get update
                apt-get install -y git
            }
        }
    }
    mkdir ~/.ssh
    chmod 700 ~/.ssh
    ssh-keyscan github.com >> ~/.ssh/known_hosts
    git clone https://github.com/mhristof/dotfiles.git ~/bin
    ~/bin/dfl
    exit 0
fi

case $(uname) in
    Linux)
        PYTHON=python
        PIP=pip
        which python &> /dev/null || {
            $SUDO apt-get update
            $SUDO apt-get install -y python-minimal
        }
        which pip &> /dev/null || {
            $SUDO apt-get install -y python-pip
        }
        ;;
    Darwin)
        PYTHON=python2.7
        PIP=pip2
        which brew &> /dev/null || {
            yes | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        }
        which $PYTHON &> /dev/null || {
            brew install python@2
            export PATH="$HOME/Library/Python/2.7/bin:/usr/local/opt/python@2/bin:$PATH"
        }
        readlink -f /dev/null &> /dev/null || {
            brew install coreutils
            export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
        }
        ;;
esac

which ansible-playbook &> /dev/null || {
    $PIP install ansible --user
}

ANSIBLE_ROLES_PATH=$(readlink -f $(dirname $0)/)
AP=$(readlink -f "$($PYTHON -m site --user-site)/../../../bin/ansible-playbook")

YAML="$(dirname "$0")/dotfiles/dotfiles.yml"

# echo ANSIBLE_ROLES_PATH=$ANSIBLE_ROLES_PATH $PYTHON $AP $YAML

ANSIBLE_ROLES_PATH=$ANSIBLE_ROLES_PATH $PYTHON $AP -i localhost, -c local $YAML -b "$@"
