#! /usr/bin/env bash
#

set -euo pipefail

AP='ansible-playbook'

function ubuntu_install {
    local prog=$1
    local apt=${2:-$prog}
    which $prog &> /dev/null || {
        echo Installing $prog: apt-get install $apt
        sudo apt-get install -y $apt 2> /tmp/apt-get-install-$prog.txt || {
            grep "E: Unable to locate package $apt" /tmp/apt-get-install-$prog.txt  && {
                sudo apt-get update
                sudo apt-get install -y $apt
            }
        }
    }
}

if [ "$EUID" -eq 0 ]; then
  echo Dont run as root
  exit 1
fi

if [[ ! -f ~/bin/dotfiles/dotfiles.yml ]]; then
    # this is the first time that we are running dfl, so clone the
    # repository and then start that dfl.
    ubuntu_install git
    ubuntu_install ssh-keyscan ssh
    [[ -d ~/.ssh ]] || mkdir -p ~/.ssh
    chmod 700 ~/.ssh
    ssh-keyscan github.com >> ~/.ssh/known_hosts
    git clone https://github.com/mhristof/dotfiles.git ~/bin
    ~/bin/dfl
    exit 0
fi

case $(uname) in
    Linux)
        PYTHON=python
        PIP=pip
        ubuntu_install python
        ubuntu_install pip python-pip
        export PATH=~/.local/bin:$PATH
        ;;
    Darwin)
        PYTHON=python2.7
        PIP=pip2
        which brew &> /dev/null || {
            yes | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        }
        export PATH="/usr/local/bin:$PATH"
        brew list python@2 &> /dev/null || {
            brew install python@2
        }
        export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
        readlink -f /dev/null &> /dev/null || {
            brew install coreutils
        }
        ;;
esac

which ansible-playbook &> /dev/null || {
    $PIP install ansible --user
}

ANSIBLE_ROLES_PATH=$(readlink -f $(dirname $0)/)
AP=$(readlink -f "$($PYTHON -m site --user-site)/../../../bin/ansible-playbook")
YAML="$(dirname "$0")/dotfiles/dotfiles.yml"

ANSIBLE_ROLES_PATH=$ANSIBLE_ROLES_PATH $PYTHON $AP -i localhost, -c local $YAML "$@"
