#!/usr/bin/env bash
set -euo pipefail

if [[ $(uname -m) == "arm64" ]] && [[ "$1" == "run" || "$1" == "build" ]]; then
    /usr/local/bin/docker "$1" --platform linux/amd64 "${@:2}"
else
    /usr/local/bin/docker "$@"
fi
