#!/usr/bin/env python3

import boto3
import argparse
import json
from tabulate import tabulate

# Initialize a session using your credentials
session = boto3.Session(
    # Optionally you can load specific credentials here
    # aws_access_key_id='YOUR_KEY',
    # aws_secret_access_key='YOUR_SECRET',
    # region_name='YOUR_REGION'
)

# Create an EC2 client from this session
ec2_client = session.client("ec2")


def fetch_all_enis(output_format):
    # Retrieve all ENIs
    response = ec2_client.describe_network_interfaces()

    # Prepare data for output
    enis_data = []

    # Process each ENI
    for eni in response["NetworkInterfaces"]:
        # Apply text wrap only for table output, not for JSON
        if output_format == "json":
            description = eni.get("Description", "No description available")
        else:
            import textwrap

            description = textwrap.fill(
                eni.get("Description", "No description available"), width=30
            )

        eni_info = {
            "ENI ID": eni["NetworkInterfaceId"],
            "Description": description,
            "Private IP": eni.get("PrivateIpAddress", "N/A"),
            "Public IP": eni.get("Association", {}).get("PublicIp", "N/A"),
            "Status": eni["Status"],
            "Subnet ID": eni["SubnetId"],
            "Attached Instance": (
                eni["Attachment"]["InstanceId"]
                if "Attachment" in eni and "InstanceId" in eni["Attachment"]
                else "Not Attached"
            ),
            "Security Groups": ", ".join([sg["GroupName"] for sg in eni["Groups"]]),
        }
        enis_data.append(eni_info)

    # Output handling based on the format
    if output_format == "json":
        print(json.dumps(enis_data, indent=4))
    else:
        # Print the table using tabulate
        table_data = [[value for value in eni.values()] for eni in enis_data]
        print(tabulate(table_data, headers="keys", tablefmt="grid"))


def main():
    parser = argparse.ArgumentParser(description="Fetch ENIs information from AWS EC2.")
    parser.add_argument(
        "-o",
        "--output",
        choices=["json", "table"],
        default="table",
        help='Output format: "json" for JSON output, "table" for tabular output.',
    )
    args = parser.parse_args()

    fetch_all_enis(args.output)


if __name__ == "__main__":
    main()
