#!/usr/bin/env bash

name="$*"

if [[ -z $name ]]; then
    echo 'Error, please provide a free text name for the feature branch'
    exit 1
fi

name="$(echo "$name" | tr -s ' ' '-')"
git checkout -b "$name"
git push --set-upstream origin "$name"
