include Makefile.yum

PIP3 := ~/.local/pip3

XZ := /usr/bin/xz

$(PIP3): $(PYTHON3)
	curl --silent -O https://bootstrap.pypa.io/get-pip.py
	python3 get-pip.py --user

/tmp/ag.rpm:
	curl --silent https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/t/the_silver_searcher-2.1.0-1.el7.x86_64.rpm > $@

/usr/bin/ag: /tmp/ag.rpm
	sudo yum install -y /tmp/ag.rpm

/usr/bin/pip3:
	sudo amazon-linux-extras install python3.8
