#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

die() {
    echo "$*" 1>&2
    exit 1
}

cat <<EOF >.mega-linter.yml
---
PRINT_ALPACA: false
DISABLE_LINTERS:
  - CREDENTIALS_SECRETLINT
  - SPELL_CSPELL
  - DOCKERFILE_DOCKERFILELINT
  - PYTHON_BANDIT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - COPYPASTE_JSCPD

MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: "(CHANGELOG.md|CONTRIBUTING.md)"
BASH_SHFMT_ARGUMENTS: "-w -i '4' -ci"
ERROR_ON_MISSING_EXEC_BIT: true
PYTHON_BLACK_DISABLE_ERRORS: false
BASH_SHFMT_DISABLE_ERRORS: false
EOF

exit 0
