#!/usr/bin/env bash
set -euo pipefail

die() {
    echo "$*" 1>&2
    exit 1
}

ID="${1:-}"
if [[ -z $ID ]]; then
    die "please provide the instance ID, for example 'i-0a393a33dbaa0e1d7'"
fi

IP=$(aws ec2 describe-instances --instance-ids "$ID" | jq '.Reservations[0].Instances[0].PublicDnsName' -r)

if [[ -z $IP ]]; then
    die "Error, instalce [$ID] doesnt have a PublicDnsName"
fi

ssh -oStrictHostKeyChecking=no "$IP"
