#!/usr/bin/env bash
# pulled from https://gist.github.com/cornet/01992fd0685484d37b6d9267ddb73c4c
#
# Based on https://github.com/corrupt952/ssm-session
#
# Requirements:
#   - fzf (brew install fzf)

set -euo pipefail

ssm_instance_ids() {
    aws ssm describe-instance-information --query "InstanceInformationList[].InstanceId" \
        --output=text
}

list_instances() {
    instance_ids=$(ssm_instance_ids)

    aws ec2 describe-instances \
        --instance-ids ${instance_ids} \
        --filter "Name=instance-state-name,Values=running" \
        --query "Reservations[*].Instances[*].[InstanceId,Tags[?Key=='Name']|[0].Value]" \
        --output text
}

run_command() {
    local command="$1"
    instance_id=$(list_instances | fzf | cut -f 1)
    aws ssm send-command --document-name "AWS-RunShellScript" \
        --parameters commands="$command" \
        --targets "Key=InstanceIds,Values=$instance_id" \
        --output text
}

print_usage() {
    cat <<-EOF
usage: ssm-session <command>
command:
    list:  List target sessions
    start: Start session manager
EOF
}

ARG=${1:-}
if [[ -z $ARG ]]; then
    ARG="start"
fi

case "$ARG" in
    list)
        list_instances

        ;;
    exec)
        CMD="${2:-}"
        if [[ -z $CMD ]]; then
            echo "Usage: $0 exec <command>"
            exit 1
        fi
        run_command "$2"
        exit 0
        ;;
    start)
        # Ignore SIGINT(Ctrl-C) to prevent accidental exit from session
        trap '' 2

        list_instances |
            fzf |
            cut -f 1 |
            xargs -o aws ssm start-session --document-name AWS-StartInteractiveCommand \
                --parameters '{"command": ["sudo -u ec2-user -g ec2-user tmuxa new -A -s mikec || bash"]}' \
                --target
        ;;
    i-*)
        PORT=$(cut -d: -f2 <<<"$ARG")
        DOCUMENT="AWS-StartInteractiveCommand"
        PARAMS='{"command": ["bash"]}'
        if [[ "$PORT" != "$ARG" ]]; then
            echo "Starting port forwarding session on port $PORT"
            DOCUMENT="AWS-StartPortForwardingSession"
            PARAMS='{"portNumber":["'$PORT'"],"localPortNumber":["'$PORT'"]}'
            ARG=$(cut -d: -f1 <<<"$ARG")
        fi
        aws ssm start-session --document-name "$DOCUMENT" \
            --parameters "$PARAMS" \
            --target "$ARG"
        ;;
    *)

        instances=$(list_instances | grep "$ARG$" | cut -f 1)

        if [[ "$(wc -l <<<"$instances")" -gt 1 ]]; then
            echo "Multiple instances found: [$instances]. Connecting to the last one"
        fi

        instance=$(tail -1 <<<"$instances")
        #  ec2-user LANG=en_US.UTF-8 TERM=ansi tmux new -A -s mikec || bash"]}' \
        aws ssm start-session --document-name AWS-StartInteractiveCommand \
            --parameters '{"command": ["sudo -u ec2-user -g ec2-user bash"]}' \
            --target "$instance"
        ;;
esac
