#!/usr/bin/env python3

import sys
import boto3
import json
import subprocess
from difflib import unified_diff


def main():
    if "-h" in sys.argv:
        print(
            """
        Usage:
            ssms <path>
            ssms cp <src> <dest>
            ssms <path>:<from_version> <path>:<to_version>
        """
        )

        return

    info = False

    if "-i" in sys.argv:
        info = True

    path = sys.argv[1] if len(sys.argv) > 1 else ""
    ssm = boto3.client("ssm")

    if path == "cp":
        if len(sys.argv) < 4:
            print("Usage: ssms cp <src> <dest>")

            return
        src = sys.argv[2]
        dest = sys.argv[3]

        src_value = ssm.get_parameter(Name=src, WithDecryption=True)["Parameter"][
            "Value"
        ]
        ssm.put_parameter(
            Name=dest, Value=src_value, Type="SecureString", Overwrite=True
        )

        return

    if not path:
        # faster to use aws cli than retrieve pages with max parameter limit of 50
        stdout = subprocess.run(
            ["aws", "ssm", "describe-parameters"], stdout=subprocess.PIPE
        ).stdout
        print("\n".join([param["Name"] for param in json.loads(stdout)["Parameters"]]))

        return

    path_parts = path.split(":")

    try:
        this = int(path_parts[-2])
        that = int(path_parts[-1])
        path = path_parts[0]
        versions = True
    except ValueError:
        versions = False
    except IndexError:
        versions = False

    if versions:
        this_value = toJsonString(
            ssm.get_parameter(Name=f"{path}:{this}", WithDecryption=True)["Parameter"][
                "Value"
            ]
        )
        that_value = toJsonString(
            ssm.get_parameter(Name=f"{path}:{that}", WithDecryption=True)["Parameter"][
                "Value"
            ]
        )

        sys.stdout.writelines(
            unified_diff(
                this_value.splitlines(keepends=True),
                that_value.splitlines(keepends=True),
                fromfile=f"{path}:{this}",
                tofile=f"{path}:{that}",
            )
        )

        return

    parameter = ssm.get_parameter(Name=path, WithDecryption=True)["Parameter"]
    value = parameter["Value"]

    print(toJsonString(value))

    if info:
        parameter.pop("Value")
        print(
            json.dumps(
                parameter,
                indent=2,
                default=str,
            )
        )


def toJsonString(data):
    try:
        return json.dumps(json.loads(data), indent=2)
    except:
        return data


if __name__ == "__main__":
    main()
