#!/usr/bin/env bash

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
source "$DIR/.lib"

TOOL=terraform
ARGS="apply -auto-approve"
TG="$(find ./ -maxdepth 2 -mindepth 2 -name terragrunt.hcl | wc -l)"

if [[ -f terragrunt.hcl ]]; then
    TOOL=terragrunt
fi

if [[ $TG -gt 0 ]]; then
    TOOL="terragrunt run-all"
fi

if [[ -f molecule/default/converge.yml ]]; then
    TOOL="molecule"
    ARGS="converge"
fi

PLAN=$(terraform_plan_name)

if [[ -f $PLAN ]]; then
    ARGS="apply $PLAN"
fi

CMD="$TOOL $ARGS"
echo "$CMD"
eval "$CMD" | tee tap.log
