#!/usr/bin/env bash
set -euo pipefail

source $HOME/bin/.lib
PATH=$(sed "s@$HOME/bin:@@" <<<"$PATH")

BIN=$(basename "$0")
which "$BIN" &>/dev/null || {
  brew install warrensbox/tap/tfswitch
}

"$BIN" "$@"
