#!/usr/bin/env bash
# :vi ft=bash:


if [[ -f id_rsa.key ]]; then
    echo 'Error id_rsa.key exists'
    exit 1
fi

if ! gpg --card-status &> /dev/null; then
    echo 'Yubikey not present'
    exit 0
fi

function generate {
    OUT=/tmp/$RANDOM
    GPG=$(gpg --card-status | grep 'General key info' | awk '{print $5}' | awk -F/ '{print $2}')
    ssh-keygen -t rsa -b 4096 -N "" -f id_rsa.key -C "Generated for yubikey $GPG"
    gpg --encrypt -r $GPG --batch --yes -o id_rsa.yubi.key.gpg id_rsa.key
    shred -u id_rsa.key
}

function load_keys {
    for f in *yubi*gpg; do
        gpg --decrypt $f | ssh-add -t 3600 -;
    done
}


case $1 in
    new)
        generate
        ;;
    load)
        load_keys
        ;;
esac
