---

- include_tasks: '{{ ansible_system|lower }}.yml'

- name: setup links
  become: false
  file:
    src: '{{ item }}'
    dest: '{{ home }}/.{{ item|basename }}'
    state: link
    force: true
  with_fileglob:
    - 'files/*'
  tags:
    - links
    - ln

- name: deploy templates
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - src: tmux.conf
      dest: '{{ home }}/.tmux.conf'
    - src: gitconfig
      dest: '{{ home }}/.gitconfig'
  tags:
    - templates

- name: wget random files
  get_url:
    url: 'https://raw.githubusercontent.com/scop/bash-completion/master/completions/make'
    dest: '{{ home }}/.bash/make_autocomplete.sh'

- name: install vundle
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: '{{ home }}/.vim/bundle/Vundle.vim'
    version: master
  tags:
    - vim

- name: install fzf
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: '{{ home }}/.fzf'
    depth: 1
  notify:
    - install fzf
  tags:
    - fzf

- name: create directories
  file:
    path: '{{ item }}'
    state: directory
    mode: 0700
  with_items:
    - '{{ home }}/.src'
    - '{{ home }}/.backup'

- name: install autojump
  git:
    repo: 'https://github.com/joelthelion/autojump.git'
    dest: '{{ home }}/.src/autojump'
    depth: 1
  notify:
    - install autojump
  tags:
    - autojump
    - aj

- name: pip install some stuff
  pip:
    name: '{{ item }}'
    state: present
    extra_args: '--user'
  with_items:
    - sh
    - readline
  tags:
    - pip

- name: 'check if {{ bin }} is an ssh checkout'
  shell: git remote -v
  register: git_remote
  changed_when: "'https' in git_remote.stdout"
  args:
    chdir: '{{ bin }}'
  notify:
    - change git remote to ssh
  tags:
    - github

- name: install oh my zsh shell
  include_tasks: oh-my-zsh.yml
  tags:
    - zsh

- include_tasks: test.yml
  tags:
    - test
