---

  - stat: path=/home/mc42/.git
    register: home_git_folder
    tags: dotfiles

 ## new repo
  - name: dotfiles | Creating new checkout
    git: repo=git@github.com:serialdoom/home.git dest=/tmp/home accept_hostkey=yes
    when: home_git_folder.stat.exists == false
  - name: Rsync git to home
    synchronize: src=/tmp/home/ dest=/home/mc42/
    when: home_git_folder.stat.exists == false
    tags: dotfiles

 ## update existing repo
  - name: dotfiles | Updating
    git: repo=git@github.com:serialdoom/home.git dest=~/
    when: home_git_folder.stat.exists == true
    tags: dotfiles

  - name: dotfiles | Creating directories
    file: path=/home/mc42/{{ item }} state=directory
    with_items: [.backup, .backup/vim, tmp, .repo]
    tags: dotfiles

