# setup github keys
---

  - stat: path=/home/mc42/.ssh/github
    register: github_private_keys
  - stat: path=/home/mc42/.ssh/config
    register: ssh_config_file
  - name: Generate github keys
    shell: ssh-keygen -t rsa -b 8192 -f ~/.ssh/github -N ''
    when: github_private_keys.stat.exists == false
  - name: Cat github pub key
    shell: cat ~/.ssh/github.pub
  - pause: prompt="Manually add the github key to github"
    when: github_private_keys.stat.exists == false
  - stat: path=~/bin/playbooks/templates/ssh_config
    register: ssh_config_template
  - file: path=/home/mc42/bin/playbooks/templates state=directory
  - get_url: url=https://raw.githubusercontent.com/serialdoom/home/master/bin/playbooks/templates/ssh_config dest=~/bin/playbooks/templates/ssh_config validate_certs=no
    when: ssh_config_template.stat.exists == false
  - template: src=~/bin/playbooks/templates/ssh_config dest=~/.ssh/config mode=0600
    when: ssh_config_file.stat.exists == false
