#sudo apt-get install ansible -y && wget https://raw.githubusercontent.com/serialdoom/home/master/bin/playbooks/ubuntu-vm-setup.yml && ansible-playbook -v -i "localhost," -c local  ubuntu-vm-setup.yml --ask-sudo-pass
---

- name: Installing core stuff
  hosts: all

  tasks:

  - name: install default packages
    apt: pkg={{ item }} state=installed update_cache=yes cache_valid_time=3600
    with_items: [binutils, git, tmux]
    sudo: yes


  - include : setup_github.yml
  - include : dotfiles.yml
  - include : vim.yml
  - include : ag.yml
  - include : pcalc.yml
