# install ag 
---

- name: ag | Cloning
  git: repo=git@github.com:ggreer/the_silver_searcher.git dest=~/.repo/the_silver_searcher accept_hostkey=yes
- name: apt-get for ag
  apt: pkg={{ item }} state=installed
  with_items: [pkg-config, liblzma-dev, make, gcc, automake, libpcre3, libpcre3-dev]
  sudo: yes
- name: ag | Building
  shell: ./build.sh chdir=~/.repo/the_silver_searcher/
- name: Ag | Linking
  file: src=~/.repo/the_silver_searcher/ag dest=~/bin/ag state=link
