---
  - name: apt-get stuff
    apt: >
      name={{ item }}
      state=present
      update_cache=yes
      cache_valid_time=3600
    with_items:
      - alsa
      - alsa-tools

  - name: add user to audio group
    user: name={{ ansible_env['USER'] }} append=yes groups=audio

