.PHONY: germ
germ: ~/bin/germ

GERM_VERSION := $(word 7,$(subst /, ,$(GERM_URL)))

$(XDG_DATA_HOME)/dotfiles/germ-$(GERM_VERSION): | $(XDG_DATA_HOME)/dotfiles
    wget --quiet $(GERM_URL) --output-document $@

~/bin/germ: $(XDG_DATA_HOME)/dotfiles/germ-$(GERM_VERSION) | ~/bin ~/.zsh.site-functions
	chmod +x $<
	ln -sf $< $@
	$@ completion zsh > ~/.zsh.site-functions/_germ || true
