.PHONY: gitbrowse
gitbrowse: ~/bin/gitbrowse

GITBROWSE_VERSION := $(word 7,$(subst /, ,$(GITBROWSE_URL)))

$(XDG_DATA_HOME)/dotfiles/gitbrowse-$(GITBROWSE_VERSION): | $(XDG_DATA_HOME)/dotfiles
    wget --quiet $(GITBROWSE_URL) --output-document $@

~/bin/gitbrowse: $(XDG_DATA_HOME)/dotfiles/gitbrowse-$(GITBROWSE_VERSION) | ~/bin ~/.zsh.site-functions
	chmod +x $<
	ln -sf $< $@
	$@ completion zsh > ~/.zsh.site-functions/_gitbrowse || true
