# Autogenerated with https://github.com/sharkdp/bat/releases/download/v0.18.3/bat-v0.18.3-x86_64-apple-Darwin.tar.gz
.PHONY: bat
bat: ~/bin/bat

BAT_VERSION := $(word 7,$(subst /, ,$(BAT_URL)))

$(XDG_DATA_HOME)/dotfiles/bat-$(BAT_VERSION).tar.gz: | $(XDG_DATA_HOME)/dotfiles
	wget --quiet $(BAT_URL) --output-document $@

$(XDG_DATA_HOME)/dotfiles/bat-$(BAT_VERSION): $(XDG_DATA_HOME)/dotfiles/bat-$(BAT_VERSION).tar.gz /usr/bin/tar
	mkdir $(XDG_DATA_HOME)/dotfiles/bat-$(BAT_VERSION)/
	tar xf $< -C $(XDG_DATA_HOME)/dotfiles/bat-$(BAT_VERSION)/

~/bin/bat: | $(XDG_DATA_HOME)/dotfiles/bat-$(BAT_VERSION)
	ln -sf $(shell find $| -name bat -type f) $@
