.PHONY: semver
semver: ~/bin/semver

SEMVER_VERSION := $(word 7,$(subst /, ,$(SEMVER_URL)))

$(XDG_DATA_HOME)/dotfiles/semver-$(SEMVER_VERSION): | $(XDG_DATA_HOME)/dotfiles
    wget --quiet $(SEMVER_URL) --output-document $@

~/bin/semver: $(XDG_DATA_HOME)/dotfiles/semver-$(SEMVER_VERSION) | ~/bin ~/.zsh.site-functions
	chmod +x $<
	ln -sf $< $@
	$@ completion zsh > ~/.zsh.site-functions/_semver || true
