.PHONY: germ
germ: ~/bin/germ

$(XDG_DATA_HOME)/dotfiles/germ-v1.13.0: | $(XDG_DATA_HOME)/dotfiles
    wget --quiet $(GERM_URL) --output-document $@

~/bin/germ: $(XDG_DATA_HOME)/dotfiles/germ-v1.13.0 | ~/bin ~/.zsh.site-functions
	chmod +x $<
	ln -sf $< $@
	$@ completion zsh > ~/.zsh.site-functions/_germ || true
