.PHONY: checkov2vim
checkov2vim: ~/bin/checkov2vim

$(XDG_DATA_HOME)/dotfiles/checkov2vim-download: | $(XDG_DATA_HOME)/dotfiles
    wget --quiet $(CHECKOV2VIM_URL) --output-document $@

~/bin/checkov2vim: $(XDG_DATA_HOME)/dotfiles/checkov2vim-download | ~/bin ~/.zsh.site-functions
	chmod +x $<
	ln -sf $< $@
	$@ completion zsh > ~/.zsh.site-functions/_checkov2vim || true
