---

- name: vim install plugins
  command: '{{ item }}'
  with_items:
    - vim +PluginInstall +qall
    - ag -au -G config 'https.*mhristof.*.git' -l | xargs -n1 perl -p -i -e 's!url = https://github.com/mhristof(.*)!url = git\@github.com:mhristof$1!'

- name: install fzf
  shell: 'yes | ./install'
  become: false
  args:
    chdir: '{{ home }}/.fzf'

- name: install autojump
  shell: './install.py'
  become: false
  environment:
    SHELL: bash
  args:
    chdir: '{{ home }}/.src/autojump'

- name: change git remote to ssh
  shell: git remote set-url origin git@github.com:mhristof/dotfiles.git
  args:
    chdir: '{{ bin }}'
