---

- name: install fzf
  shell: 'yes | ./install'
  become: false
  args:
    chdir: '{{ home }}/.fzf'

- name: install autojump
  shell: './install.py'
  become: false
  environment:
    SHELL: bash
  args:
    chdir: '{{ home }}/.src/autojump'

- name: change git remote to ssh
  shell: git remote set-url origin git@github.com:mhristof/dotfiles.git
  args:
    chdir: '{{ home }}/bin'
