name: ci

on:
  - push

jobs:
  build:
    strategy:
      matrix:
        platform:
        #- ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - run: make brew # zsh dev
