name: ci

on:
  - push

jobs:
  build:
    strategy:
      matrix:
        include:
          - image: macos-latest
    runs-on: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v4
      - run: make zsh dots vim
        shell: bash
        env:
          SHELL: /bin/bash

  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: mhristof/github-action-automerge@v1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
