name: ci

on:
  - push

jobs:
  build:
    strategy:
      matrix:
        include:
          - image: ubuntu-latest
          - image: macos-latest
            fix: |
              # macos fix for https://github.com/Homebrew/homebrew-core/pull/71996
              make brew || true
              mv .github/perl.rb /Users/runner/.brew/Library/Taps/homebrew/homebrew-core/Formula/perl.rb || true
          - image: ubuntu-latest
            cmdPrefix: "make amazon-test; docker run --rm dotfiles-amazon"
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - run: ${{ matrix.fix }}
      - run: ${{ matrix.cmdPrefix }} make zsh dev
