name: ci

on:
  - push

jobs:
  build:
    strategy:
      matrix:
        platform:
        #- ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - run: make brew
      - run: mv perl.rb /Users/runner/.brew/Library/Taps/homebrew/homebrew-core/Formula/perl.rb
      - run: make vim || cat /Users/runner/Library/Logs/Homebrew/perl/02.make
